### ISSUE TITLE
Add offshore areas polygons

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/hazdev-geoserve-ws#160]
Greg has the data. This is for Hydra to use. we would want to document this as well,

**Comment by gsmoczyk** [comment]
The data file is called "feoffshore.dat" and can be found at:

\\hazshares\ghsc\gsmoczyk\GEOSERVE

Dataset Documentation:  These regions are from the original FE Plus dataset and provide "offshore" polygons to Hydra in areas where earthquakes are a common occurrence.

**Comment by ehunter-usgs** [comment]
If someone wants to pick this up, I have the data added to the install process and everything baked into the webservice. I am not currently getting results and I'm not sure why, but my local postgresql database doesn't appear to think that I have postgis enabled.

Also, if the map looks funny, that's because leaflet.css is not linked. See #164 

Everything I have is here:
https://github.com/ehunter-usgs/hazdev-geoserve-ws/tree/usgs/hazdev-geoserve-ws%23160

Need:
 - Offshore region view (with example page)
 - Add view to LocationApp
